### ISSUE TITLE
Error trying to Brew

### ISSUE THREAD

**Issue by comccoy** [mwunsch/tumblr#32]
I am sure this is something simple but I am not sure how to get past this:

bash-3.2$ brew install https://raw.github.com/mwunsch/tumblr/master/share/tumblr-rb.rb
###### ################################################################## 100.0%

==> gem install tumblr-rb --version 2.0.0 --no-rdoc --no-ri --install-dir /usr/l
ERROR:  Error installing tumblr-rb:
    weary requires rack (~> 1.4.0, runtime)

READ THIS: https://github.com/mxcl/homebrew/wiki/troubleshooting

bash-3.2$

**Comment by mwunsch** [comment]
This is an issue w/ gem dependencies.
- Tumblr-rb depends on `sinatra ~> 1.3.2`, which currently will resolve to [Sinatra v1.3.6](https://rubygems.org/gems/sinatra/versions/1.3.6)
- Sinatra v1.3.6 has a dependency on `rack ~> 1.4`, this will resolve to the latest Rack v1.5.2
- Tumblr-rb depends on `weary ~> 1.1.0`, which resolves to [Weary v1.1.2](https://rubygems.org/gems/weary).
- Weary v1.1.2 has a dependency on `rack ~> 1.4.0`, which resolves to [Rack v1.4.5](https://rubygems.org/gems/rack/versions/1.4.5)

So the dependencies of the tumblr-rb gem conflict here: Rack v1.4.5 (brought in by Weary) VERSUS Rack v1.5.2 (brought in by Sinatra).

To resolve these dependencies, we should update the gemspec to be less restrictive in what it accepts, and run tests on newer versions of Rack/Sinatra.

**In the meantime**, You can successfully brew by downloading the raw brew file, and edit this line:

``` ruby
    system "gem", "install", "tumblr-rb",
             "--version", "2.0.0",
             "--no-rdoc", "--no-ri",
             "--install-dir", prefix
```

Add this extra flag: `"--include-dependencies"`. You can then `brew install` by pointing to the local file. This could be weird, since you're going to install multiple versions of Rack, and I would normally say "DON'T DO THIS", but I don't think this particular case is harmful.

Dependencies are hard. Patch to fix is coming soon.
