### ISSUE TITLE
Add editing capabilities to the CLI

### ISSUE THREAD

**Issue by mwunsch** [mwunsch/tumblr#4]
Since posting with the CLI echoes out the new Post ID to the console, it would be great to be able to have a `tumblr edit` command that takes that post id and allows you to edit that post.

My thought is to have something similar to git, when committing without specifying a message. It opens up your editor and on save, finishes the commit. 

The `tumblr edit POST-ID` command would pull down the post, convert to YAML, and output to EDITOR, and when saved, would publish to tumblr.

**Comment by RobertAudi** [comment]
I would love this feature. I think one of the following solutions would be simpler though:
- Keep track of the published posts. So for instance, everytime a post is published, an entry would be added to a hidden file `.published` with the name of the file and the corresponding ID.
- Add the post ID of the published posts to the top of the post file, either automatically (if it's possible) or manually.

Either of those solution would make something like `tumblr edit path/to/post` possible; and passing the filename instead of the post id is more intuitive imho.

The method above obviously assumes that the posts are in a specific folder (ie: `~/tumblr/{posts,drafts,etc}` and not in some random location.

**Comment by mwunsch** [comment]
Aziz: This does not take into account what happens if you were to publish a post with the tumblr gem. Edit that post with Tumblr.com, and then edit the post again with the cli. Or what about posts you would like to edit that you created on tumblr.com?

I'm also not a big fan of a CLI assuming it can just grab your disk space and save files (hidden or otherwise) willy-nilly. With that kind of behavior, you must also build in options to modify default settings and it overcomplicates the tool, IMO.

**Comment by mwunsch** [comment]
This is in master now.
